name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      #run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD   

    - name: Build the Frontend Docker image
      run: docker build -t timothyfudocker/frontendapp4:latest -f ./frontendapp4/Dockerfile .
      
    - name: Tag the Docker image with v.1.01
      run: docker tag timothyfudocker/frontendapp4:latest timothyfudocker/frontendapp4:v.1.01

    - name: Push Frontend Docker image to Dockerhub
      run: docker push timothyfudocker/frontendapp4:latest

    - name: Push the Docker image (v.1.01 tag)
      run: docker push timothyfudocker/frontendapp4:v.1.01